/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iphone16_v2.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle010: THREE.Mesh
    Circle011: THREE.Mesh
    Circle012: THREE.Mesh
    Circle013: THREE.Mesh
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube001_3: THREE.Mesh
    Cube001_4: THREE.Mesh
    Cube001_5: THREE.Mesh
    Cube001_6: THREE.Mesh
    Cube015: THREE.Mesh
    Cube002: THREE.Mesh
    Cube002_1: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Cylinder022: THREE.Mesh
    len11001: THREE.Mesh
    len22001: THREE.Mesh
    len33001: THREE.Mesh
    Object003: THREE.Mesh
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane012: THREE.Mesh
    Plane013: THREE.Mesh
    Plane014: THREE.Mesh
    Sphere010: THREE.Mesh
    Sphere011: THREE.Mesh
    Sphere012: THREE.Mesh
    Sphere013: THREE.Mesh
  }
  materials: {
    ['black.002']: THREE.MeshStandardMaterial
    ['basecolor.001']: THREE.MeshStandardMaterial
    ['metalframe.002']: THREE.MeshStandardMaterial
    ['apple logo.001']: THREE.MeshStandardMaterial
    ['screen.001']: THREE.MeshStandardMaterial
    ['metaL.001']: THREE.MeshStandardMaterial
    ['glass.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['gray.001']: THREE.MeshStandardMaterial
    lensinglass: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/iphone16_v2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle010.geometry} material={materials['black.002']} position={[-0.076, 0.619, 0.136]} rotation={[Math.PI / 2, -1.571, 0]} scale={0.038} />
      <mesh geometry={nodes.Circle011.geometry} material={materials['black.002']} position={[-0.263, 0.719, 0.135]} rotation={[Math.PI / 2, -1.571, 0]} scale={0.017} />
      <mesh geometry={nodes.Circle012.geometry} material={materials['black.002']} position={[-0.262, 0.52, 0.136]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.024} />
      <mesh geometry={nodes.Circle013.geometry} material={materials['black.002']} position={[-0.081, 0.786, 0.01]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.016} />
      <group position={[-0.011, 0.023, 0.053]} rotation={[0, -1.57, 0]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['black.002']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['basecolor.001']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['metalframe.002']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['apple logo.001']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials['screen.001']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials['metaL.001']} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials['glass.002']} />
      </group>
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.001']} position={[-0.002, -0.794, 0.057]} rotation={[0, -1.57, 0]} />
      <group position={[0.013, 0.785, 0.042]} rotation={[0, -1.57, 0]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['black.002']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['glass.002']} />
      </group>
      <group position={[0.374, -0.06, 0.052]} scale={0.015}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['black.002']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['metalframe.002']} />
      </group>
      <group position={[-0.263, 0.718, 0.11]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.083, 0.026, 0.083]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['black.002']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['metalframe.002']} />
      </group>
      <group position={[-0.261, 0.52, 0.11]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.083, 0.026, 0.083]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['black.002']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['metalframe.002']} />
      </group>
      <group position={[-0.076, 0.619, 0.11]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.083, 0.026, 0.083]}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['black.002']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['metalframe.002']} />
      </group>
      <group position={[-0.077, 0.759, 0.08]} rotation={[0, -1.57, 0]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['metalframe.002']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Cylinder022.geometry} material={materials['black.002']} position={[-0.077, 0.478, 0.065]} rotation={[Math.PI / 2, -1.571, 0]} scale={0.033} />
      <mesh geometry={nodes.len11001.geometry} material={materials['glass.002']} position={[-0.263, 0.718, 0.11]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.083, 0.026, 0.083]} />
      <mesh geometry={nodes.len22001.geometry} material={materials['glass.002']} position={[-0.076, 0.619, 0.11]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.083, 0.026, 0.083]} />
      <mesh geometry={nodes.len33001.geometry} material={materials['glass.002']} position={[-0.261, 0.52, 0.11]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.083, 0.026, 0.083]} />
      <mesh geometry={nodes.Object003.geometry} material={materials['gray.001']} position={[-0.002, -0.806, 0.054]} rotation={[0, -1.57, 0]} />
      <group position={[-0.166, 0.635, 0.115]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.199}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['basecolor.001']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['glass.002']} />
      </group>
      <mesh geometry={nodes.Plane012.geometry} material={materials['metalframe.002']} position={[-0.019, 0.512, 0.118]} rotation={[1.66, -0.781, 0.126]} scale={0.004} />
      <mesh geometry={nodes.Plane013.geometry} material={materials['metaL.001']} position={[-0.126, -0.813, 0.054]} rotation={[-3.137, -0.787, 0.013]} scale={0.011} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['metaL.001']} position={[0.195, -0.816, 0.053]} rotation={[-3.137, -0.787, 0.013]} scale={0.011} />
      <mesh geometry={nodes.Sphere010.geometry} material={materials.lensinglass} position={[-0.263, 0.719, 0.129]} rotation={[0, -1.57, 0]} scale={[0.006, 0.013, 0.013]} />
      <mesh geometry={nodes.Sphere011.geometry} material={materials.lensinglass} position={[-0.262, 0.52, 0.13]} rotation={[0, -Math.PI / 2, 0]} scale={[0.01, 0.021, 0.021]} />
      <mesh geometry={nodes.Sphere012.geometry} material={materials.lensinglass} position={[-0.076, 0.619, 0.13]} rotation={[0, -1.57, 0]} scale={[0.006, 0.029, 0.029]} />
      <mesh geometry={nodes.Sphere013.geometry} material={materials.lensinglass} position={[-0.081, 0.786, 0.015]} rotation={[0, Math.PI / 2, 0]} scale={[0.005, 0.012, 0.012]} />
    </group>
  )
}

useGLTF.preload('/iphone16_v2.glb')
